@isTest (isParallel = true)
private class M4_Examples_Test {
	@isTest
	static void testCreatingLists() {
		M4_Examples m4Examples = new M4_Examples();
		m4Examples.creatingLists();
	}

	@isTest
	static void testInitializingLists() {
		M4_Examples m4Examples = new M4_Examples();
		m4Examples.initializingLists();
	}

	@isTest
	static void testUniqueAccountIds() {
		M4_Examples m4Examples = new M4_Examples();
		m4Examples.uniqueAccountIds();
	}

	@isTest
	static void testMapsExample() {
		M4_Examples m4Examples = new M4_Examples();
		m4Examples.mapsExample();
	}

	@isTest
	static void testExtractingSetFromMap() {
		M4_Examples m4Examples = new M4_Examples();
		m4Examples.extractingSetFromMap();
	}

	@isTest
	static void testAnActualDictionary() {
		M4_Examples m4Examples = new M4_Examples();
		m4Examples.anActualDictionary();
	}

	@isTest
	static void testCheckingMapKeys() {
		M4_Examples m4Examples = new M4_Examples();
		m4Examples.checkingMapKeys();
	}

	@isTest
	static void testBooleanExpressions() {
		M4_Examples m4Examples = new M4_Examples();
		m4Examples.booleanExpressions();
	}

	@isTest
	static void testConstructingClasses() {
		M4_Examples m4Examples = new M4_Examples();
		m4Examples.constructingClasses();
	}

	@isTest
	static void testAccessingAPrivateString() {
		M4_Examples m4Examples = new M4_Examples();
		m4Examples.accessingAPrivateString();
	}
}