@isTest (isParallel = true)
public class M5_Examples_Test {

	@isTest
	static void testListOrSetIterationForLoop() {
		M5_Examples examples = new M5_Examples();
		examples.listOrSetIterationForLoop();
	}

	@isTest
	static void testReferencingListElements() {
		M5_Examples examples = new M5_Examples();
		examples.referencingListElements();
	}

	@isTest
	static void testTraditionalForLoop() {
		M5_Examples examples = new M5_Examples();
		examples.traditionalForLoop();
	}

	@isTest
	static void testSpeedyForLoop() {
		M5_Examples examples = new M5_Examples();
		examples.speedyForLoop();
	}

	@isTest
	static void testWhileLoop() {
		M5_Examples examples = new M5_Examples();
		examples.whileLoop();
	}

	@isTest
	static void testDoWhileLoop() {
		M5_Examples examples = new M5_Examples();
		examples.doWhileLoop();
	}
}